server:
  port: 8083
  servlet:
    context-path: /notification

notification:
  email:
    brevo-url: "${BREVO_API_URL:https://api.brevo.com/v3}"
    brevo-apikey: "${BREVO_API_KEY:}"

spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: "${SPRING_DATA_MONGODB_URI:mongodb://root:root@localhost:27017/notification-service?authSource=admin}"

  kafka:
    consumer:
      bootstrap-servers: "${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}"
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.devteria.event.dto.NotificationEvent

jwt:
  signerKey: "${JWT_SIGNER_KEY:1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij}"
