server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bookteria_identity}"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: "${SPRING_DATASOURCE_USERNAME:root}"
    password: "${SPRING_DATASOURCE_PASSWORD:root}"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: "${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  signerKey: "${JWT_SIGNER_KEY:1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij}"
  valid-duration: 3600        # 1 giờ (seconds)
  refreshable-duration: 86400 # 24 giờ (seconds)

app:
  services:
    profile:
      url: "${PROFILE_SERVICE_URL:http://localhost:8085/profile}"
