<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.devteria</groupId>
    <artifactId>book-project-root</artifactId>
    <version>1.0.0</version>
    <!-- Định dạng pom báo hiệu đây là project chứa các project con -->
    <packaging>pom</packaging>

    <!-- Liệt kê tên các thư mục service của bạn vào đây -->
    <modules>
        <module>identity-service</module>
        <module>api-gateway</module>
        <module>file-service</module>
        <module>chat-service</module>
        <module>notification-service</module>
        <module>post-service</module>
        <module>profile-service</module>
        <!-- Thêm các module khác nếu có -->
    </modules>

</project>