server:
  port: 8084
  servlet:
    context-path: /post

app:
  services:
    profile:
      url: "${PROFILE_SERVICE_URL:http://profile-service:8085}"

spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: "${SPRING_DATA_MONGODB_URI:mongodb://root:root@localhost:27017/post-service?authSource=admin}"

jwt:
  signerKey: "${JWT_SIGNER_KEY:1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij}"