server:
  port: 8085
  servlet:
    context-path: /profile

spring:
  # Cấu hình Neo4j
  neo4j:
    uri: "${SPRING_NEO4J_URI:bolt://localhost:7687}"
    authentication:
      username: "${SPRING_NEO4J_AUTHENTICATION_USERNAME:neo4j}"
      password: "${SPRING_NEO4J_AUTHENTICATION_PASSWORD:12345678}"

jwt:
  signerKey: "${JWT_SIGNER_KEY:1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij}"