server:
  port: 8082
  servlet:
    context-path: /chat

app:
  services:
    profile:
      url: "${PROFILE_SERVICE_URL:http://localhost:8085}"

spring:
  application:
    name: chat-service
  data:
    mongodb:
      uri: "${SPRING_DATA_MONGODB_URI:mongodb://root:root@localhost:27017/chat-service?authSource=admin}"
      auto-index-creation: true

jwt:
  signerKey: "${JWT_SIGNER_KEY:1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij}"